"""
Chess Coach - Game Analyzer

Reads captured games from chess/games/ and produces improvement reports.
Run via Cline skill: /chess-coach
"""

import json
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

GAMES_DIR = Path(__file__).resolve().parent.parent / "games"
OUTPUT_DIR = Path(__file__).resolve().parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)


def load_games() -> list[dict]:
    """Load all game files from the games directory."""
    games = []
    for f in sorted(GAMES_DIR.glob("*.json"), reverse=True):
        try:
            with open(f) as fh:
                games.append(json.load(fh))
        except (json.JSONDecodeError, OSError) as e:
            print(f"  [WARN] Could not read {f.name}: {e}")
    return games


def analyze_openings(games: list[dict]) -> dict:
    """Analyze opening patterns across games."""
    # Simple opening detection based on first few moves
    openings = Counter()
    for game in games:
        moves = game.get("moves", [])
        if len(moves) >= 4:
            # Use first 2 moves per side as opening signature
            first_fens = [m["fen"] for m in moves[:4]]
            opening_key = " > ".join(first_fens)
            openings[opening_key] += 1

    return {
        "total_games": len(games),
        "unique_openings": len(openings),
        "most_common": openings.most_common(5),
    }


def analyze_mistakes(games: list[dict]) -> dict:
    """Analyze move patterns to identify common mistakes."""
    total_moves = 0
    games_with_data = 0

    for game in games:
        moves = game.get("moves", [])
        if moves:
            games_with_data += 1
            total_moves += len(moves)

    return {
        "games_with_data": games_with_data,
        "total_moves_captured": total_moves,
        "avg_moves_per_game": round(total_moves / max(games_with_data, 1), 1),
    }


def analyze_performance(games: list[dict]) -> dict:
    """Analyze win/loss/draw performance."""
    results = Counter()
    for game in games:
        result = game.get("result", "unknown")
        results[result] += 1

    total = max(sum(results.values()), 1)
    return {
        "results": dict(results.most_common()),
        "win_rate": round((results.get("1-0", 0) + results.get("You won!", 0)) / total * 100, 1),
    }


def generate_report(games: list[dict]) -> str:
    """Generate a full improvement report."""
    if not games:
        return "# Chess Coach Report\n\nNo games found in `chess/games/`. Play some games on chess.com with the extension active first."

    openings = analyze_openings(games)
    mistakes = analyze_mistakes(games)
    performance = analyze_performance(games)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# Chess Coach Improvement Report
**Generated:** {now}
**Games analyzed:** {len(games)}

---

## Performance Overview

| Metric | Value |
|--------|-------|
| Total Games | {len(games)} |
| Win Rate | {performance['win_rate']}% |
| Total Moves Captured | {mistakes['total_moves_captured']} |
| Avg Moves/Game | {mistakes['avg_moves_per_game']} |

### Results Breakdown
"""
    for result, count in performance["results"].items():
        report += f"  - {result}: {count}\n"

    report += f"""
---

## Opening Analysis

You played {openings['unique_openings']} different opening patterns across {openings['total_games']} games.

### Most Frequent Positions
"""
    for opening, count in openings["most_common"]:
        report += f"  - {opening} ({count}x)\n"

    report += f"""
---

## Improvement Areas

Based on the captured game data, here are areas to focus on:

### 1. Review Your Games
Each captured game is saved in `chess/games/`. Review them to identify:
- Where did you lose material?
- Which openings felt uncomfortable?
- Did you run out of time in critical positions?

### 2. Study Your Openings
Your most-played openings are listed above. Pick ONE and learn:
- The main line (3-4 moves deep)
- Common tactical motifs in that opening
- Typical middlegame plans

### 3. Tactical Training
Most games below 1500 Elo are decided by tactics. Recommended:
- 10-15 minutes of puzzles daily
- Focus on: forks, pins, discovered attacks
- Use Chess.com's puzzle rush for pattern recognition

---

## Recommendations

1. **Play longer time controls** (15+10) to give yourself time to think
2. **Review every game** after playing — especially losses
3. **Focus on one opening** as White and one as Black
4. **Do tactics daily** — consistency beats intensity

---

*Report generated by Oxy Chess Coach. Play more games to get deeper insights.*
"""

    return report


def main():
    print("=" * 60)
    print("  OXY CHESS COACH - Game Analysis")
    print("=" * 60)

    games = load_games()
    print(f"\n  Found {len(games)} game(s) in {GAMES_DIR}\n")

    report = generate_report(games)

    # Save report
    report_path = OUTPUT_DIR / "latest-report.md"
    with open(report_path, "w") as f:
        f.write(report)

    print(report)
    print(f"\n  Report saved to: {report_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()